#!/bin/bash
# script to clean all payloads generated by avoidz
# cleanup files generated by avoidz
while true; do
    read -p "[*] clean up files? (Y/n) = " yn
    case $yn in
    [Yy]* ) rm /root/c1.exe > /dev/null 2>&1;rm /root/c2.exe > /dev/null 2>&1;rm /root/cs.exe > /dev/null 2>&1;rm /root/py.exe > /dev/null 2>&1;rm /root/go.exe > /dev/null 2>&1;echo " Files removed [ ✔ ]";exit;;
    [Nn]* ) echo "";echo "Good Bye!";echo "";exit;;
    esac
done

exit
